<?php
global $wdimex_exe, $tmpdir, $outdir, $wdm_messagefile;

$adminemail = 'rburghol@vt.edu';
// database connection info
// main modeling database
$dbname = 'cbp';
$dbpass = 'reim@nn';
$dbuser = 'robertwb';
$dbip = '192.168.0.21';
$cbp_port = 5434;
// session data database
$session_dbname = 'model_sessiondata';
$session_dbpass = '314159';
$session_dbuser = 'postgres';

$serverip = 'deq1.bse.vt.edu';
$mapservip = '66.16.215.162';
$mapserv_cgi = 'mapserv'; # would be mapserv.exe under windows
# google api key
$gapikey = 'ABQIAAAAA7WL0moYTPBf2u-kPTUd8hRKiZoKD3So9JJj0y8UgDbMWqHU6BQb6dwnEQOo4BC2rtm42hw8EAfERw';

$sitename = 'OM is Online Object-Oriented Meta-Modeling';
$defaultpage = 'medit_modeling2.php';

# absolute path to where you put the who php files
$httproot = "/var/www/html";
$httppath = '/var/www/html';
$httppath_nodrive = '/var/www/html';
# absolute path to where you put the who php files
$basedir = "$httppath/om/";
$basedir_nodrive = "$httppath/om/";
$baseurl = '/om';

# the next two entries, datadir and dataurl are
# used to allow a single place for data storage 
# accessed from live and dev versions
# these should therefore point to the liver version
$datadir = "$httppath/data"; 
$outdir = "$httppath/data/proj3/out"; 
$dataurl = '/data';
# absolute path to where you put the lib files
$libpath = "/var/www/html/lib";
# URL to library folder
$liburl = '/lib';
# url to javascript
$scripturl = '/scripts';

# URL to the web server writable directory, your jpgraph install needs to be configured to write to this directory
$gouturl = "/tmp";
$iconurl = "/images";

# need a writeable temp dir. if using widgets that execute dos commands, one may wish to have this be a short, 8.3 compliant dirname
# such as C:/temp or /tmp (if using unix dos ports)
$tmpdir = "/var/www/html/tmp";
$shellcopy = 'cp'; # the local system copy command for shell scripts that use it

# default for graphics generated by jpgraph
$default_imagetype = 'png';

# HSPF specific info
$wdm_messagefile = '/opt/model/cbp_wsm/p532c/hspf/lib3.2/lib_data/message.wdm';
$hspf_exe = '/var/www/cgi-bin/hspf';
$wdimex_exe = '/opt/model/cbp_wsm/p532c/hspf/lib3.2/bin/wdimex';

# local executable for php
$php_exe = "/var/www/cgi-bin/php";

?>
