<?php
//error_reporting(E_ALL);
$adminemail = 'rburghol@vt.edu';
// database connection info
// main modeling database
$dbname = 'model';
$dbpass = 'reim@nn';
$dbuser = 'robertwb';
//$dbip = '192.168.0.13'; // deq3
$dbip = '192.168.0.21'; // dbase2
$cbp_dbip = '192.168.0.21'; // dbase1
$cbp_port = 5434;
// session data database
$session_dbname = 'model_sessiondata';
$session_dbpass = '314159';
$session_dbuser = 'postgres';
$session_dbip = 'localhost';
$session_port = 5433;

// runtime modeling database
// use this if we want to NOT have a main postgresql database port active, 
// for instance, when reserving the main port for a failover replicant
$runtime_dbname = 'model_scratch';
$runtime_dbpass = '314159';
$runtime_dbuser = 'postgres';
$runtime_dbip = 'localhost';
$runtime_dbport = '5433';

$remote_run = TRUE;
//vwuds database connection
$vwuds_dbname = 'vwuds';
$vwuds_dbpass = '314159';
$vwuds_dbuser = 'wsp_ro';
//$vwuds_dbip = 'localhost';
// deq1

$serverip = 'deq2.bse.vt.edu';
$mapservip = '66.16.215.162';
$mapserv_cgi = 'mapserv'; # would be mapserv.exe under windows
# google api key
$gapikey = 'ABQIAAAAA7WL0moYTPBf2u-kPTUd8hSpxCV4KUwMR8tyB6kYVprcA33vJxTUyO8Pd0KshKNw8YTmJ-y9GxOGcA';

$sitename = 'OM is Object-oriented Meta-modeling';
$defaultpage = 'medit_modeling2.php';

# absolute path to where you put the who php files
$httproot = "/var/www/html";
$httppath = '/var/www/html';
$httppath_nodrive = '/var/www/html';
# absolute path to where you put the who php files
$basedir = "$httppath/om/";
$basedir_nodrive = "$httppath/om/";
$baseurl = '/om';

# the next two entries, datadir and dataurl are
# used to allow a single place for data storage 
# accessed from live and dev versions
# these should therefore point to the liver version
$datadir = "$httppath/wooomm/dirs"; 
$dataurl = '/wooomm/dirs';
# absolute path to where you put the lib files
$libpath = "/var/www/html/lib";
$libdir = "/var/www/html/lib";
# URL to library folder
$liburl = '/lib';
# url to javascript
$scripturl = '/scripts';

# URL to the web server writable directory, your jpgraph install needs to be configured to write to this directory
$gouturl = "/tmp";
$iconurl = "/images";

# need a writeable temp dir. if using widgets that execute dos commands, one may wish to have this be a short, 8.3 compliant dirname
# such as C:/temp or /tmp (if using unix dos ports)
$tmpdir = "/var/www/html/tmp";
$shellcopy = 'cp'; # the local system copy command for shell scripts that use it

# default for graphics generated by jpgraph
$default_imagetype = 'png';

# HSPF specific info
$wdm_messagefile = '/var/www/cgi-bin/message.wdm';
$hspf_exe = '/var/www/cgi-bin/hspf';
$wdimex_exe = '/var/www/cgi-bin/wdimex';

# local executable for php
$php_exe = "/var/www/cgi-bin/php";

?>
